name: 'Verify ARM64 Image'
description: 'Verify that Docker images are built for ARM64 architecture'

inputs:
  image_name:
    description: 'Docker image name to verify'
    required: true
  image_tag:
    description: 'Docker image tag to verify'
    required: true

runs:
  using: "composite"
  steps:
    - name: 🔍 Verify ARM64 architecture
      shell: bash -leo pipefail {0}
      run: |
        echo "Verifying ARM64 architecture for image: ${{ inputs.image_name }}:${{ inputs.image_tag }}"
        
        # Check if image exists and has ARM64 variant
        docker buildx imagetools inspect ${{ inputs.image_name }}:${{ inputs.image_tag }} || {
          echo "❌ Image not found or not accessible"
          exit 1
        }
        
        # Verify ARM64 architecture is present
        if docker buildx imagetools inspect ${{ inputs.image_name }}:${{ inputs.image_tag }} | grep -q "linux/arm64"; then
          echo "✅ ARM64 architecture found in image"
        else
          echo "❌ ARM64 architecture not found in image"
          exit 1
        fi
        
        echo "✅ Image verification completed successfully" 