apiVersion: v1
kind: ConfigMap
metadata:
  name: devsu-demo-config
  namespace: devsu-demo-prod
  labels:
    app: devsu-demo
    environment: production
    component: config
data:
  NODE_ENV: "production"
  PORT: "8000"
  LOG_LEVEL: "warn"
  DATABASE_HOST: "mariadb-service"
  DATABASE_PORT: "3306"
  DATABASE_NAME: "devsu_demo"
  FORCE_SYNC: "false" 