apiVersion: v1
kind: Secret
metadata:
  name: devsu-demo-secrets
  namespace: devsu-demo-prod
  labels:
    app: devsu-demo
    environment: production
    component: secrets
type: Opaque
data:
  DATABASE_USER:
  DATABASE_PASSWORD:
  JWT_SECRET:
  SESSION_SECRET: