inputs:
  aws_region:
    description: 'AWS runner region'
    default: 'us-east-1'
    required: false
  environment:
    description: 'Target environment to deploy'
    required: true
  version:
    description: 'Version to deploy as a git reference (branch, tag)'
    required: true
  docker_username:
    description: 'Docker Hub username'
    required: true
  docker_password:
    description: 'Docker Hub password'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check version
      shell: bash -leo pipefail {0}
      run: python3 --version

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}