services:
  # MariaDB Database for Development
  mariadb-dev:
    image: mariadb:11.8
    platform: linux/arm64
    container_name: devsu-mariadb-dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${DATABASE_PORT:-3306}:3306"
    volumes:
      - mariadb_data_dev_mariadb:/var/lib/mysql
      - mariadb_logs_dev_mariadb:/var/log/mysql
    networks:
      - app-network-dev-mariadb

volumes:
  mariadb_data_dev_mariadb:
    driver: local
  mariadb_logs_dev_mariadb:
    driver: local

networks:
  app-network-dev-mariadb:
    driver: bridge 