version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
      target: runner
    container_name: devsu-nodejs-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8000/api/users', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  # Reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: devsu-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - production

volumes:
  app_data:
    driver: local
  app_logs:
    driver: local

networks:
  app-network:
    driver: bridge 