version: '3.8'

services:
  # MariaDB Database for Production
  mariadb:
    image: mariadb:11.8
    platform: linux/arm64
    container_name: devsu-mariadb-prod
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: /run/secrets/db_password
      MARIADB_DATABASE: devsu_demo
      MARIADB_USER: admin
      MARIADB_PASSWORD: /run/secrets/db_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_logs:/var/log/mysql
    secrets:
      - db_password
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
      target: runner
      platforms:
        - linux/amd64
        - linux/arm64
    platform: linux/arm64
    container_name: devsu-nodejs-api-prod
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - DATABASE_NAME=devsu_demo
      - DATABASE_USER=admin
    secrets:
      - db_password
      - jwt_secret
      - session_secret
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
    restart: unless-stopped
    networks:
      - app-network

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    platform: linux/arm64
    container_name: devsu-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mariadb_data:
    driver: local
  mariadb_logs:
    driver: local
  app_data:
    driver: local
  app_logs:
    driver: local

networks:
  app-network:
    driver: bridge

# TODO: before deploying to production, ensure that the secrets are created (setup-secrets.sh)
secrets:
  db_password:
    file: secrets/db_password.txt
  jwt_secret:
    file: secrets/jwt_secret.txt
  session_secret:
    file: secrets/session_secret.txt 