services:
  # MariaDB Database
  mariadb:
    image: mariadb:11.8
    platform: linux/arm64
    container_name: devsu-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT:-3306}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_logs:/var/log/mysql
    networks:
      - app-network

  app:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
      target: runner
      platforms:
        - linux/amd64
        - linux/arm64
    platform: linux/arm64
    container_name: devsu-nodejs-api
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=mariadb
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
    restart: unless-stopped
    networks:
      - app-network

  # Reverse proxy for production
  nginx:
    image: nginx:alpine
    platform: linux/arm64
    container_name: devsu-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - production

volumes:
  mariadb_data:
    driver: local
  mariadb_logs:
    driver: local
  app_data:
    driver: local
  app_logs:
    driver: local

networks:
  app-network:
    driver: bridge 