version: '3.8'

services:
  app-staging:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
      target: runner
    container_name: devsu-nodejs-api-staging
    ports:
      - "8001:8000"
    env_file:
      - .env.staging
    environment:
      - NODE_ENV=staging
    volumes:
      - app_data_staging:/app/data
      - app_logs_staging:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network-staging

  # Nginx reverse proxy for staging
  nginx-staging:
    image: nginx:alpine
    container_name: devsu-nginx-staging
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-staging
    restart: unless-stopped
    networks:
      - app-network-staging

volumes:
  app_data_staging:
    driver: local
  app_logs_staging:
    driver: local

networks:
  app-network-staging:
    driver: bridge 