apiVersion: v1
kind: ConfigMap
metadata:
  name: devsu-demo-config
  namespace: devsu-demo-staging
  labels:
    app: devsu-demo
    environment: staging
    component: config
data:
  NODE_ENV: "staging"
  PORT: "8000"
  LOG_LEVEL: "info"
  DATABASE_NAME: "./data/test-db.sqlite"
  FORCE_SYNC: "false" 