apiVersion: v1
kind: ConfigMap
metadata:
  name: devsu-demo-config
  namespace: devsu-demo-staging
  labels:
    app: devsu-demo
    environment: staging
    component: config
data:
  NODE_ENV: "staging"
  PORT: "8000"
  LOG_LEVEL: "info"
  DATABASE_HOST: "mariadb-service"
  DATABASE_PORT: "3306"
  DATABASE_NAME: "devsu_demo_staging"
  FORCE_SYNC: "false" 