apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devsu-demo-hpa
  namespace: devsu-demo-staging
  labels:
    app: devsu-demo
    environment: staging
    component: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devsu-demo-app
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 