apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: devsu-demo-staging
  labels:
    app: mariadb
    environment: staging
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
      environment: staging
  template:
    metadata:
      labels:
        app: mariadb
        environment: staging
        component: database
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.8
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mariadb-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: MYSQL_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 5