apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devsu-demo-sqlite-pvc
  namespace: devsu-demo-staging
  labels:
    app: devsu-demo
    environment: staging
    component: database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" 