apiVersion: v1
kind: Secret
metadata:
  name: devsu-demo-secrets
  namespace: devsu-demo-staging
  labels:
    app: devsu-demo
    environment: staging
    component: secrets
type: Opaque
data:
  DATABASE_USER: YWRtaW4=
  DATABASE_PASSWORD: YWRtaW4=
  JWT_SECRET: YWRtaW4=
  SESSION_SECRET: YWRtaW4=