name: 'Set environment variables'
description: 'Set ENVIRONMENT and other variables'

runs:
  using: "composite"
  steps:
    - name: Determine environment
      shell: bash -l {0}
      run: |
        env | grep GITHUB_
        set_env() { echo "$1" >> $GITHUB_ENV; }

        DEV_EVENTS=(push pull_request workflow_dispatch)
        DEFAULT_BRANCH=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
        CURRENT_REF=${GITHUB_REF##*/}

        if [[ "$CURRENT_REF" =~ ^v([0-9]{8})(-[0-9]{2})$ ]]; then
          set_env "ENVIRONMENT=production"
        elif [[ "$CURRENT_REF" =~ "$DEFAULT_BRANCH" ]]; then
          set_env "ENVIRONMENT=stage"
        elif [[ "${DEV_EVENTS[*]}" =~ "$GITHUB_EVENT_NAME" ]]; then
          set_env "ENVIRONMENT=stage"
        else
          echo "Error:"
          echo "The tag created for this deployment does not match defined conventions."
          echo "Check the README's 'Releases and deployments' section for more details."
          exit 1
        fi
