name: Node.js Version Check

on:
  pull_request:
    branches:
      - stage
  push:
    tags:
      - 'v[0-9]{8}-*'

jobs:
  show-node-version-on-pr:
    if: github.event_name == 'pull_request' && github.base_ref == 'stage'
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar versión de Node.js
        run: node --version

  show-node-version-on-tag:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar versión de Node.js
        run: node --version

