name: Node.js Version Check

on:
  pull_request:
    branches:
      - stage
  push:
    branches:
      - main
    tags:
      - 'v[0-9]{8}-*'

jobs:
  show-node-version-on-pr:
    if: github.event_name == 'pull_request' && github.base_ref == 'stage'
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar versión de Node.js - PR
        run: node --version
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  show-node-version-on-tag:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar versión de Node.js - Tag
        run: node --version
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  show-node-version-on-main-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar versión de Node.js - Main Branch
        run: node --version
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
